#!/bin/bash

export DISPLAY=:1
SESSNAME="qemucon"
SESSPATH="/dos/runimages/$SESSNAME"

set -e
set -x

if [ "`cat /dos/startconsole`" = 0 ]; then
  echo "qemuconsole startup disabled by /dos/startconsole; not starting."
  supervisorctl stop qemuviewer || true
  sleep 900d
  exit 0
fi

BASEIMAGE="${BASEIMAGE:-/dos/baseimages/freedos-c-minimal.qcow2.gz}"
if [ ! -d "$SESSPATH" ]; then
  mksessimg "$BASEIMAGE" "$SESSNAME"
fi

waitfordaemon vncserver true
waitfordaemon smbd true
waitfordaemon nmbd true
waitfordaemon tcpsercon true

cd "$SESSPATH"
#echo "D:" >> drive_d/BOOTUP.BAT
#echo "cd ADF" >> drive_d/BOOTUP.BAT
#echo "lh adf COM1 3F8  4 115200 8192  8192  8" >> drive_d/BOOTUP.BAT
#echo "CD \\" >> drive_d/BOOTUP.BAT

# In case the user starts without the TCP stack
cp -r /dos/drive_g/* drive_d/
cp -r /dos/drive_h/* drive_d/
unix2dos drive_d/BOOTUP.BAT

set +e
qemu-system-i386 -localtime \
   -m 32M \
   "$SESSPATH/c.qcow2" -boot c \
   -hdb "fat:$SESSPATH/drive_d" \
   -net nic,model=pcnet -net user \
   -name "$SESSNAME" -vnc :2
   -chardev socket,id=com1,host=localhost,port=7000 -device isa-serial,chardev=com1
RETCODE="$?"
exit "$RETCODE"

