#!/bin/bash

set -e

MAXNODE=${BBSNODES:-`cat /dos/numnodes`}
FOUNDNODE=""

for NODE in `seq 1 $MAXNODE`; do
  if ! check-dosemu-session node$NODE &> /dev/null; then
    FOUNDNODE="$NODE"
    break
  fi
done

if [ -z "$FOUNDNODE" ]; then
  echo "All nodes are busy now; please try again later."
  exit 1
fi

SESSNAME=node$FOUNDNODE
STARTUP=/dos/drive_h/STARTUP/NODE$FOUNDNODE.BAT

# Hook to let node prep happen
if [ -e /dos/nodeprephook.sh ]; then
  . /dos/nodeprephook.sh
fi

echo "Welcome to node $FOUNDNODE.  Please stand by while we connect you..."
exec startdossession $SESSNAME "H:\\STARTUP\\NODE$FOUNDNODE"

