#!/bin/bash

set -e

MAXNODE=${BBSNODES:-`cat /dos/numnodes`}

if [ "$MAXNODE" -lt 1 ]; then
  echo "Configured for $MAXNODE nodes; exiting."
  exec sleep 900d
  exit 1 # just to be sure
fi

CMDLINE=""

for NODE in `seq 1 $MAXNODE`; do
  NODEVPORT=$(($NODE + 8000))
  CMDLINE="$CMDLINE -v $NODEVPORT -s 115200"
done

set -x
exec /usr/bin/tcpser $CMDLINE -p 23

